### ISSUE TITLE
Resistor values for R1 / R2 / R5 / R6 and R3? 

### ISSUE THREAD

**Issue by modeler** [svenpetersen1965/C64-Diagnostic-Rev.-586220-Harness#1]
Firstly, thank you Sven for sharing this. I'm looking to build one of these myself but when verifying the resistor values I think I found something odd. The documentation says R3 is a 320 ohm resistor, however in the photo it looks like something different (the others check out).

Looking at [Jerzy Sobola's schematic on Zimmers.net](http://www.zimmers.net/anonftp/pub/cbm/schematics/cartridges/c64/diag/diag-c64-8k.gif) R3 is a 300 ohm resistor rather than 320 ohm, he also uses 100k resistors for R1, R2, R5 and R6 rather than 120k.

I'd be very grateful if you or anyone else could help me understand why these are different, thanks in advance.

**Comment by svenpetersen1965** [comment]
Hi,
I have used a 316 Ohm resistor instead of 320. I guess, 330R works as well. Sorry, I should update the part list. The 120k resistors are used to determin the value, the sid returns for potx and poty for both ports. I would not change it. It works fine, here. 

Mit freundlichen Grüßen/Kind regards
Sven Petersen

Enzianweg 16
83052 Bruckmühl
Germany

Fon: +49 8062 728125
Email: sven@guitarsite.de
Web: http://www.guitarsite.de

**Comment by modeler** [comment]
Legend, thanks for explaining and for getting back to me so quickly.
